// Package agent generates and updates GEMINI.md (and SPUR.md) so that
// coding agents always know exactly what protocols and modules are available
// in the current project. This is updated every time spur add runs.
package agent

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/ranakdinesh/spur-cli/internal/config"
	"github.com/ranakdinesh/spur-cli/internal/protocol"
)

// Regenerate rewrites GEMINI.md and SPUR.md from the current project state.
// Called by: spur new, spur add protocol, spur add module
func Regenerate(state *config.ProjectState) error {
	content := generate(state)

	if err := os.WriteFile("GEMINI.md", []byte(content), 0644); err != nil {
		return fmt.Errorf("write GEMINI.md: %w", err)
	}
	if err := os.WriteFile("SPUR.md", []byte(content), 0644); err != nil {
		return fmt.Errorf("write SPUR.md: %w", err)
	}
	return nil
}

func generate(state *config.ProjectState) string {
	var sb strings.Builder

	sb.WriteString("# SPUR PROJECT — AGENT GUIDE\n")
	sb.WriteString(fmt.Sprintf("> Generated by spur CLI on %s\n", time.Now().Format("2006-01-02 15:04")))
	sb.WriteString("> Read this completely before writing any code.\n\n")
	sb.WriteString("---\n\n")

	// ── Project identity ──────────────────────────────────────────────────
	sb.WriteString("## 1. PROJECT IDENTITY\n\n")
	sb.WriteString(fmt.Sprintf("**Name:** %s\n", state.Name))
	sb.WriteString(fmt.Sprintf("**Go module:** %s\n", state.GoModule))
	sb.WriteString("\n---\n\n")

	// ── What is enabled ───────────────────────────────────────────────────
	sb.WriteString("## 2. ENABLED PROTOCOLS\n\n")
	sb.WriteString("These protocols are running. Use them. Do not rebuild them.\n\n")

	for _, pid := range state.Protocols {
		p, ok := protocol.Find(pid)
		if !ok {
			continue
		}
		port := state.ProtocolPorts[pid]
		if port != "" {
			sb.WriteString(fmt.Sprintf("### %s (port %s)\n", strings.ToUpper(pid), port))
		} else {
			sb.WriteString(fmt.Sprintf("### %s\n", strings.ToUpper(pid)))
		}
		sb.WriteString(p.AgentNote)
		sb.WriteString("\n\n")
	}

	sb.WriteString("---\n\n")

	// ── Installed modules ─────────────────────────────────────────────────
	sb.WriteString("## 3. INSTALLED MODULES\n\n")
	if len(state.Modules) == 0 {
		sb.WriteString("No modules installed yet. Run: spur add module identity\n\n")
	} else {
		sb.WriteString("| Module | Purpose |\n|--------|--------|\n")
		for _, m := range state.Modules {
			sb.WriteString(fmt.Sprintf("| %s | see internal/modules/%s/MODULE.md |\n", m, m))
		}
		sb.WriteString("\n")
	}
	sb.WriteString("---\n\n")

	// ── How to use protocols in code ──────────────────────────────────────
	sb.WriteString("## 4. HOW TO USE PROTOCOLS IN MODULE CODE\n\n")
	sb.WriteString("Protocols are available via the `infra` parameter in `module.Mount(infra)`.\n\n")

	if hasProtocol(state, "grpc") {
		sb.WriteString("```go\n// Register gRPC service in module Mount()\nfunc (m *Module) Mount(infra *platform.Infra) error {\n    pb.RegisterMyServiceServer(infra.GRPC.Server, myGRPCImpl)\n    return nil\n}\n```\n\n")
	}
	if hasProtocol(state, "websocket") {
		sb.WriteString("```go\n// Send WebSocket message from anywhere\ninfra.WS.BroadcastTenant(tenantID, wsserver.Message{Type: \"event\", Payload: data})\ninfra.WS.BroadcastUser(userID, wsserver.Message{Type: \"notification\", Payload: data})\n```\n\n")
	}
	if hasProtocol(state, "sse") {
		sb.WriteString("```go\n// SSE streaming endpoint\nfunc (h *Handler) Stream(w http.ResponseWriter, r *http.Request) {\n    ch := infra.SSE.Subscribe(userID.String())\n    defer infra.SSE.Unsubscribe(userID.String(), ch)\n    sseserver.WriteHeaders(w)\n    for msg := range ch { sseserver.WriteEvent(w, msg); w.(http.Flusher).Flush() }\n}\n// Publish from anywhere:\ninfra.SSE.Publish(userID.String(), sseserver.Event{Data: payload})\n```\n\n")
	}
	if hasProtocol(state, "queue") {
		sb.WriteString("```go\n// Publish to queue\ninfra.Queue.Publish(ctx, \"module:event\", payload)\n\n// Subscribe in module Mount()\ngo infra.Queue.Subscribe(ctx, \"module:event\", func(msg queue.Message) error {\n    // handle msg.Data\n    return nil\n})\n```\n\n")
	}
	if hasProtocol(state, "temporal") {
		sb.WriteString("```go\n// Start a workflow\ninfra.Temporal.ExecuteWorkflow(ctx,\n    client.StartWorkflowOptions{ID: \"unique-id\", TaskQueue: \"mymodule-queue\"},\n    MyWorkflow, input)\n\n// Register worker in module Mount()\nif infra.Temporal != nil {\n    w := worker.New(*infra.Temporal, \"mymodule-queue\", worker.Options{})\n    w.RegisterWorkflow(MyWorkflow)\n    w.RegisterActivity(MyActivity)\n    go w.Run(worker.InterruptCh())\n}\n```\n\n")
	}
	if hasProtocol(state, "hls") {
		sb.WriteString("```go\n// Create an HLS stream\nplaybackURL, err := infra.HLS.CreateStream(streamKey)\n// Playback: http://host:8888/hls/{streamKey}/index.m3u8\n// Ingest:   rtmp://host:1935/live/{streamKey}\n```\n\n")
	}

	sb.WriteString("---\n\n")

	// ── Module pattern ────────────────────────────────────────────────────
	sb.WriteString("## 5. MODULE PATTERN (copy exactly)\n\n")
	sb.WriteString("```go\n")
	sb.WriteString(fmt.Sprintf(`package mymodule

type Options struct {
    DB  *pgxpool.Pool
    Log *logger.Loggerx
    Cfg Config
`))
	if hasProtocol(state, "websocket") {
		sb.WriteString("    WS  *wsserver.Hub\n")
	}
	if hasProtocol(state, "sse") {
		sb.WriteString("    SSE *sseserver.Broker\n")
	}
	if hasProtocol(state, "temporal") {
		sb.WriteString("    Temporal *temporalclient.Client\n")
	}
	if hasProtocol(state, "queue") {
		sb.WriteString("    Queue *queue.Queue\n")
	}
	sb.WriteString(`}

func New(ctx context.Context, opt Options) (*Module, error) {
    // 1. Run migrations
    // 2. Wire repos
    // 3. Wire services
    // 4. Wire handlers
    return &Module{Manifest: manifest}, nil
}

func (m *Module) RegisterRoutes(r chi.Router) {
    r.Route("/mymodule", func(r chi.Router) { /* handlers */ })
}
`)
	if hasProtocol(state, "grpc") {
		sb.WriteString(`func (m *Module) RegisterGRPC(srv *grpcserver.Server) {
    pb.RegisterMyServiceServer(srv.Server, m.grpcImpl)
}
`)
	}
	sb.WriteString("```\n\n")

	sb.WriteString("---\n\n")

	// ── Rules ─────────────────────────────────────────────────────────────
	sb.WriteString("## 6. RULES — NEVER VIOLATE\n\n")
	sb.WriteString("- NEVER rebuild auth — identity module handles it\n")
	sb.WriteString("- NEVER import another module's package\n")
	sb.WriteString("- NEVER write to identity.* DB tables\n")
	sb.WriteString("- NEVER use fmt.Printf — use opt.Log\n")
	sb.WriteString("- NEVER call os.Exit inside modules — return errors\n")
	sb.WriteString("- ALWAYS get tenantID from context: httpserver.GetTenantID(r.Context())\n")
	sb.WriteString("- ALWAYS scope DB queries by tenant_id\n")
	sb.WriteString("- Application tables: public schema only\n")

	if hasProtocol(state, "grpc") {
		sb.WriteString("- gRPC auth: use the JWT interceptor — it sets tenant/user in context\n")
	}
	if hasProtocol(state, "websocket") {
		sb.WriteString("- WebSocket auth: JWT in query param ?token= — hub validates on connect\n")
	}
	if hasProtocol(state, "temporal") {
		sb.WriteString("- Temporal: always check `if infra.Temporal != nil` before using\n")
	}

	sb.WriteString("\n---\n\n")

	// ── Build verify ──────────────────────────────────────────────────────
	sb.WriteString("## 7. BUILD + VERIFY\n\n")
	sb.WriteString("```bash\nmake sqlc          # after adding sql/queries/*.sql\n")
	sb.WriteString("go build ./...     # must output nothing\n")
	sb.WriteString("make docker-up     # starts everything\n")
	sb.WriteString("curl http://localhost:8080/healthz  # expect 200\n")
	if hasProtocol(state, "grpc") {
		sb.WriteString("grpcurl -plaintext localhost:9090 list  # expect service list\n")
	}
	if hasProtocol(state, "temporal") {
		sb.WriteString("# Temporal UI: http://localhost:8081 (if started with --profile temporal)\n")
	}
	sb.WriteString("# Grafana:     http://localhost:3001 (logs + metrics)\n")
	sb.WriteString("```\n\n")

	// ── What to add next ──────────────────────────────────────────────────
	sb.WriteString("## 8. ADD MORE LATER\n\n")
	sb.WriteString("```bash\nspur add protocol grpc       # add a protocol\n")
	sb.WriteString("spur add protocol temporal   # add Temporal\n")
	sb.WriteString("spur add module billing      # add a module\n")
	sb.WriteString("spur status                  # see what's installed\n")
	sb.WriteString("```\n")

	return sb.String()
}

func hasProtocol(state *config.ProjectState, id string) bool {
	return state.HasProtocol(id)
}
